# Generated by Django 3.2 on 2021-08-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20210815_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='wishlist_user',
        ),
    ]
