# Generated by Django 3.2 on 2021-08-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_rename_product_wishlist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='name',
        ),
    ]
