# Generated by Django 3.2 on 2021-08-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_remove_wishlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
