# Generated by Django 3.2 on 2021-06-16 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews_list',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
