# Generated by Django 3.2 on 2021-08-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_shoe_sizes'),
        ('reviews_list', '0004_alter_reviews_list_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews_list',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='products.product'),
        ),
    ]
