# Generated by Django 5.0 on 2023-12-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
