# Generated by Django 3.2 on 2021-05-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_product_product_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_item',
            old_name='name',
            new_name='title',
        ),
    ]
