# Generated by Django 5.0 on 2023-12-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_name_product_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
