# Generated by Django 3.2 on 2021-05-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_shoe_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
